package com.cmc.dashboard.model;
// Generated Apr 19, 2018 7:49:45 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Issue generated by hbm2java
 */
@Entity
@Table(name = "issue")
public class Issue implements Serializable {

	private static final long serialVersionUID = -7208540685230130391L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "issue_id", unique = true, nullable = false)
	private int issueId;

	@ManyToOne(optional = false)
	@JoinColumn(name = "issue_category_id")
	private IssueCategory issueCategory;

	@ManyToOne(optional = false)
	@JoinColumn(name = "issue_priority_id")
	private IssuePriority issuePriority;

	@ManyToOne(optional = false)
	@JoinColumn(name = "issue_serverity_id")
	private IssueServerity issueServerity;

	@ManyToOne(optional = false)
	@JoinColumn(name = "issue_source_id")
	private IssueSource issueSource;

	@ManyToOne(optional = false)
	@JoinColumn(name = "issue_status_id")
	private IssueStatus issueStatus;

	@ManyToOne(optional = false)
	@JoinColumn(name = "issue_type_id")
	private IssueType issueType;

	@ManyToOne(optional = true)
	@JoinColumn(name = "closed_by", nullable = true)
	private User usersByClosedBy;

	@ManyToOne(optional = true)
	@JoinColumn(name = "approved_by", nullable = true)
	private User usersByApprovedBy;

	@ManyToOne(optional = false)
	@JoinColumn(name = "created_by")
	private User usersByCreatedBy;

	@Column(name = "description", nullable = false, length = 500)
	private String description;

	@Column(name = "cause", nullable = false, length = 500)
	private String cause;

	@Column(name = "project_id")
	private Integer projectId;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "open_date", length = 19)
	private Date openDate;

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	private Date dueDate;

	@Column(name = "suggestion_of_qa", nullable = true,  length = 500)
	private String suggestionOfQa;

	@Column(name = "action", nullable = true,  length = 500)
	private String action;

	@Column(name = "comment", length = 500)
	private String comment;

	@Column(name = "impact", length = 500)
	private String impact;
	
	@Column(name = "assignee", nullable = true)
	private Integer assignee;
	
	@Column(name = "deleted", nullable = false, columnDefinition = "tinyint(1) default 0")
	private Boolean deleted;

	public Issue() {
	}

	public Issue(int issueId, String description, String cause) {
		this.issueId = issueId;
		this.description = description;
		this.cause = cause;
	}

	public Integer getIssueId() {
		return this.issueId;
	}

	public void setIssueId(int issueId) {
		this.issueId = issueId;
	}

	public IssueCategory getIssueCategory() {
		return this.issueCategory;
	}

	public void setIssueCategory(IssueCategory issueCategory) {
		this.issueCategory = issueCategory;
	}

	public IssuePriority getIssuePriority() {
		return this.issuePriority;
	}

	public void setIssuePriority(IssuePriority issuePriority) {
		this.issuePriority = issuePriority;
	}

	public IssueServerity getIssueServerity() {
		return this.issueServerity;
	}

	public void setIssueServerity(IssueServerity issueServerity) {
		this.issueServerity = issueServerity;
	}

	public IssueSource getIssueSource() {
		return this.issueSource;
	}

	public void setIssueSource(IssueSource issueSource) {
		this.issueSource = issueSource;
	}

	public IssueStatus getIssueStatus() {
		return this.issueStatus;
	}

	public void setIssueStatus(IssueStatus issueStatus) {
		this.issueStatus = issueStatus;
	}

	public IssueType getIssueType() {
		return this.issueType;
	}

	public void setIssueType(IssueType issueType) {
		this.issueType = issueType;
	}

	public User getUsersByClosedBy() {
		return this.usersByClosedBy;
	}

	public void setUsersByClosedBy(User usersByClosedBy) {
		this.usersByClosedBy = usersByClosedBy;
	}

	public User getUsersByApprovedBy() {
		return this.usersByApprovedBy;
	}

	public void setUsersByApprovedBy(User usersByApprovedBy) {
		this.usersByApprovedBy = usersByApprovedBy;
	}

	public User getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(User usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public String getSuggestionOfQa() {
		return this.suggestionOfQa;
	}

	public void setSuggestionOfQa(String suggestionOfQa) {
		this.suggestionOfQa = suggestionOfQa;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getImpact() {
		return this.impact;
	}

	public void setImpact(String impact) {
		this.impact = impact;
	}

	public Integer getAssignee() {
		return assignee;
	}

	public void setAssignee(Integer assignee) {
		this.assignee = assignee;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
