package com.cmc.dashboard.model;
// Generated Apr 19, 2018 7:49:45 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * IssueServerity generated by hbm2java
 */
@Entity
@Table(name = "issue_serverity")
public class IssueServerity implements Serializable {

	private static final long serialVersionUID = 766273790539084363L;

	@TableGenerator(name = "Issue_Serverity_Gen", table = "ID_GEN", pkColumnName = "GEN_KEY", valueColumnName = "GEN_VALUE", pkColumnValue = "issue_serverity_id", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "Issue_Serverity_Gen")
	@Column(name = "issue_serverity_id", unique = true, nullable = false)
	private int id;

	@Column(name = "value", length = 45)
	private String value;

	@Column(name = "deleted")
	private Boolean deleted;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "issueServerity")
	@JsonIgnore
	private Collection<Issue> issues;

	public IssueServerity() {
	}

	public IssueServerity(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Collection<Issue> getIssues() {
		return issues;
	}

	public void setIssues(Collection<Issue> issues) {
		this.issues = issues;
	}

}
