package com.cmc.dashboard.model;
// Generated Apr 19, 2018 7:49:45 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Collection;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * IssueType generated by hbm2java
 */
@Entity
@Table(name = "issue_type")
public class IssueType implements Serializable {

	private static final long serialVersionUID = 9055246179766677871L;

	@TableGenerator(name = "Issue_Type_Gen", table = "ID_GEN", pkColumnName = "GEN_KEY", valueColumnName = "GEN_VALUE", pkColumnValue = "issue_type_id", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "Issue_Type_Gen")
	@Column(name = "issue_type_id", unique = true, nullable = false)
	private int id;

	@Column(name = "value", length = 45)
	private String value;

	@Column(name = "deleted")
	private Boolean deleted;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "issueType")
	@JsonIgnore
	private Collection<Issue> issues;

	public IssueType() {
	}

	public IssueType(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Collection<Issue> getIssues() {
		return issues;
	}

	public void setIssues(Collection<Issue> issues) {
		this.issues = issues;
	}

}
